### ISSUE TITLE
update postgres_docker readme with user defined network instructions

### ISSUE THREAD

**Issue by lynnjo** [solgenomics/postgres_dockerfile#1]
Currently, the postgres_docker README page shows connecting containers via the --link command.  That docker command is deprecated.  the README should provide an example of using user-defined networks for cross-container communications.

**Comment by timparsons** [comment]
Thanks for adding this @lynnjo!! I moved what you added in the README to the [breedbase_dockerfile](https://github.com/solgenomics/breedbase_dockerfile) repo.
